### ISSUE TITLE
Composer install fails because of PHP 5.6 requirement

### ISSUE THREAD

**Issue by sherblot** [Cloudstek/whmcs-mollie-payment-gateway#1]
Hello,

I'm trying to install this module on a server with PHP 5.4.1 installed on it. The module is marked as compatible with PHP 5.3+ but the at least one of its dependencies is not:

```
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=5.6 but your PHP version (5.4.1) does not satisfy that requirement.
  Problem 2
    - Installation request for cloudstek/mollie-php-api 2.0.0 -> satisfiable by cloudstek/mollie-php-api[2.0.0].
    - cloudstek/mollie-php-api 2.0.0 requires php >=5.6 -> your PHP version (5.4.1) does not satisfy that requirement.
```

Which breaks the PHP 5.3+ compatibility. 

Regards,
Sebastien

**Comment by sherblot** [comment]
After investigation, the problem is coming from the composer.lock file (https://github.com/Cloudstek/whmcs-mollie-payment-gateway/blob/master/mollie/composer.lock) that is still looking for the version 2.0.0.

A simple `composer update` fixed the issue on my side. an update of the composer.lock file to use the version 2.0.1 of the dependency `cloudstek/mollie-php-api` will fix the issue.

**Comment by mdeboer** [comment]
I'll fix this right away, thanks for reporting!

**Comment by mdeboer** [comment]
It has fixed though which such a minor so shortly after release I have decided to keep the version at 1.0.0. If you re-download this release the problem should be fixed. Thank you so much for reporting! 👍
