### ISSUE TITLE
Autoloader not working

### ISSUE THREAD

**Issue by doriejanni** [Cloudstek/whmcs-mollie-payment-gateway#4]
I am trying to use this plugin with my WHMCS installation, but I can't run composer on my server. Can someone who has this plugin running send me the contents of their autoload.php file, so I can use that one for my install?

**WHMCS version:** 7.0.2
**PHP version:** 5.6.30
**Mollie payment gateway version:** current

**Enabled addons:**

No addons enabled

**Enabled payment gateways:**

No payment gateways enabled

**Relevant gateway log output:**

**Additional information:**

* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem started happening recently: Yes
* Problem can be reproduced in an older version: Yes

**Comment by mdeboer** [comment]
Please download the release locally, run composer and then upload the files to your server. I will look into releasing a full version with all dependencies included but at the moment that's not a priority. Please let me know if you have any further issues.
