### ISSUE TITLE
Fatal Error after composer install

### ISSUE THREAD

**Issue by MaikelVEGroup** [Cloudstek/whmcs-mollie-payment-gateway#5]
After doing step 3 I get this: Fatal error: Uncaught Error: Class 'WHMCS\Utility\ErrorManagement' not found in /home/maikelve/my.maikelve.com/init.php:0 Stack trace: #0 /home/maikelve/my.maikelve.com/admin/index.php(0): unknown() #1 {main} thrown in /home/maikelve/my.maikelve.com/init.php on line 0

**WHMCS version:** 7.2.2
**PHP version:** 7.0
**Mollie payment gateway version:** latest
**Theme:** control, latets version

**Comment by MaikelVEGroup** [comment]
And after importing the files i get this when i go to the payment methodes: 

Whoops\Exception\ErrorException: require_once(): Failed opening required '/home/maikelve/my.maikelve.com/modules/gateways/mollie/vendor/autoload.php' (include_path='.:/opt/alt/php70/usr/share/pear') in /home/maikelve/my.maikelve.com/modules/gateways/mollie.php:11
Stack trace:
#0 /home/maikelve/my.maikelve.com/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/home/maikelve/...', 11)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by mdeboer** [comment]
Hi @MaikelVEGroup, couple of questions:

- Does this also occur with an older version of WHMCS or does this only occur with 7.2.2?

- Where did you run composer (step 3)? I'm not sure what you mean by "importing the files" but your second stack trace suggests that the vendor/autoload.php file cannot be found, which is what step 3 creates. Please make sure you run step 3 in `/home/maikelve/my.maikelve.com/modules/gateways/mollie/`.
